config/routes.rb
require 'sidekiq/web'
Survey::Application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web
  mount ActionCable.server => "/cable"
end



Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :responses
  resources :questions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "questions#index"
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :responses, dependent: :destroy

  after_create_commit -> { broadcast_prepend_to "questions", partial: "questions/question", locals: { question: index_row, response: Response.new, current_user_signed_in: Current.user_signed_in }, target: "questions" }

  def self.index_page
    find_by_sql(self.response_counts)
  end

  def index_row
    @index_row ||= Question.find_by_sql(response_count(id)).first
  end

  def self.response_counts
    <<SQL
      WITH rc AS (select question_id, count(case when answer = 0 then answer end) as no_count,
             count(case when answer = 1 then answer end) as yes_count
      FROM responses
      GROUP BY question_id)

      SELECT q.id, q.question, q.user_id, u.username, rc.no_count, rc.yes_count
          FROM questions q LEFT JOIN rc on q.id = rc.question_id
          LEFT JOIN users u on q.user_id = u.id
          ORDER BY q.created_at DESC;
SQL
  end
  def response_count(qid)
    <<SQL
      WITH rc AS (select question_id, count(case when answer = 0 then answer end) as no_count,
             count(case when answer = 1 then answer end) as yes_count
      FROM responses
      WHERE question_id = #{qid}
      GROUP BY question_id)

      SELECT q.id, q.question, q.user_id, u.username, rc.no_count, rc.yes_count
          FROM questions q LEFT JOIN rc on q.id = rc.question_id
          LEFT JOIN users u on q.user_id = u.id
          WHERE q.id = #{qid}
          ORDER BY q.created_at DESC;
SQL
  end

  def response
    Response.find_by_question_id_and_user_id(id, user_id) || Response.new
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [ :index ]

  # GET /questions or /questions.json
  def index
    @questions = Kaminari.paginate_array(Question.index_page).page(params[:page]).per(10)
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_url, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to questions_url, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy!

    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end


    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:question, :user_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper

end

app/views/questions/_form.html.erb
<%= turbo_frame_tag "question_form_frame" do %>
  <%= bootstrap_form_for(question) do |form| %>
    <% if question.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

        <ul>
          <% question.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div style="width:50%">
      <%= form.text_area :question %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
<% end %>

app/views/questions/_no_pct.html.erb
<td class="center" id=<%= dom_id(local_assigns[:question], :no) %> ><%= no_pct(local_assigns[:question].yes_count, local_assigns[:question].no_count) || 0 %></td>

app/views/questions/_question.html.erb
    <tr>
      <td width="55%"><%= question.question %> </td>
      <td><%= question.username %></td>
      <%= render 'questions/yes_pct', question: question %>
      <%= render 'questions/no_pct', question: question %>
      <% if local_assigns[:current_user_signed_in] %>
        <td>
          <turbo_frame id=<%= dom_id(question, :response_form_frame) %>>
            <%= render "responses/form", question: question, response: local_assigns[:response]  %>
          </turbo_frame>
        </td>
      <% end %>
      <% if local_assigns[:current_user_signed_in] %>
        <td>
          <%= button_to question, class: "btn shadow-none", :method=> :delete,
                        data: { bs_toggle: "tooltip",
                                bs_title: "Delete this question",
                                bs_placement: 'right',
                                turbo_method: :delete,
                                turbo_confirm: "Are you sure you want to delete #{question.question}?" } do %>
            <i class="bi-trash" style="font-size: 1rem; color: red;"></i>
          <% end %>
        </td>
      <% end %>
    </tr>

    <script type=application/javascript>

  var tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
  var tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))

</script>

app/views/questions/_yes_pct.html.erb
<td class="center" id=<%= dom_id(local_assigns[:question], :yes) %> ><%= yes_pct(local_assigns[:question].yes_count, local_assigns[:question].no_count) || 0 %></td>

app/views/questions/edit.html.erb
<% content_for :title, "Editing question" %>

<h1>Editing question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Show this question", @question %> |
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/index.html.erb
<%= turbo_stream_from "questions" if Current.user_signed_in %>


<% content_for :title, "Surveys" %>

<div class="container-md">
  <% if Current.user_signed_in %>
    <div class="right-just">
      <%= button_to(
            "Log Out #{current_user.username}",
            destroy_user_session_path,
            method: :delete,
            class: 'btn btn-warning'
          ) %>
    </div>

    <%= render "form", question: Question.new %>

  <% else %>
    <p></p>
    <%= button_to(
          "Log In to Add or Respond to a Question",
          new_user_session_path,
          method: :GET,
          class: 'btn btn-success'
        ) %>
  <% end %>
  
  <p></p>

  <div class="container-sm">
    <div class="right-just">
      <%= paginate @questions %>
    </div>
    <table class="table table-striped table-bordered table-small">
      <thead>
      <th scope="col">Question</th>
      <th scope="col">Added By</th>
      <th class="center" scope="col">Yes's</th>
      <th class="center" scope="col">No's</th>
      <% if Current.user_signed_in %>
        <th scope="col">Response</th>
        <th></th>
      <% end %>
      </thead>
      <tbody id="questions" class="table-group-divider">
      <turbo-stream action="prepend" target="questions">
        <template>
          <% @questions.each do |question| %>
            <% response = Response.find_by_question_id_and_user_id(question.id, current_user.id) || Response.new if Current.user_signed_in %>
            <%= render question, response: response, current_user_signed_in: Current.user_signed_in %>
          <% end %>
        </template>
      </turbo-stream>
      </tbody>
    </table>
    <div class="right-just">
      <%= paginate @questions %>
    </div>
  </div>
</div>

<!--<%#= link_to "New question", new_question_path %></br>-->

app/views/questions/new.html.erb
<% content_for :title, "New question" %>

<h1>New question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @question %>

<div>
  <%= link_to "Edit this question", edit_question_path(@question) %> |
  <%= link_to "Back to questions", questions_path %>

  <%= button_to "Destroy this question", @question, method: :delete %>
</div>