config/routes.rb
require 'sidekiq/web'
Survey::Application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web
  mount ActionCable.server => "/cable"
end



Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :responses
  resources :questions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "questions#index"
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: %i[ show edit update destroy ]

  # GET /responses or /responses.json
  def index
    @responses = Response.all
  end

  # GET /responses/1 or /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses or /responses.json
  def create
    @response = Response.new(response_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @response.save
        format.html { redirect_to question_url, notice: "Response was successfully created." }
        format.turbo_stream { render :update }
        format.json { render :show, status: :created, location: @response }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @response.errors, status: :unprocessable_entity }
        format.turbo_stream { redirect_to questions_url, notice: "An error occurred creating response." }
      end
    end
  end

  # PATCH/PUT /responses/1 or /responses/1.json
  def update
    respond_to do |format|
      if @response.update(response_params.merge(user_id: current_user.id))
        format.html { redirect_to question_url, notice: "Response was successfully updated." }
        format.turbo_stream { render :update }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @response.errors, status: :unprocessable_entity }
        format.turbo_stream { redirect_to questions_url, notice: "An error occurred updating response." }
      end
    end
  end

  # DELETE /responses/1 or /responses/1.json
  def destroy
    @response.destroy!

    respond_to do |format|
      format.html { redirect_to responses_url, notice: "Response was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response
      @response = Response.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def response_params
      params.require(:response).permit(:answer, :question_id)
    end
end

app/helpers/responses_helper.rb
module ResponsesHelper
  def yes_pct(yes_count, no_count)
    return pct(yes_count, no_count)
  end
  def no_pct(yes_count, no_count)
    return pct(no_count, yes_count)
  end
  def pct(numerator, denominator)
    return nil if numerator.nil? || denominator.nil?
    return nil if numerator + denominator == 0
    number_to_percentage((numerator.to_f / (numerator + denominator)) * 100, precision: 1)
  end
end

app/views/responses/_form.html.erb
  <% q = defined?(question) && !question.nil? ? question : local_assigns[:question] %>
  <%= form_with(model: local_assigns[:response], html: { name: 'response-form' }) do |form| %>
    <div>
      Yes&nbsp; <%= form.radio_button :answer, :yes, data: { controller: 'authentic' }, onclick: "this.response-form.requestSubmit();" %>
      &nbsp;No&nbsp; <%= form.radio_button :answer, :no, data: { controller: 'authentic' }, onclick: "this.response-form.requestSubmit();" %>
      <%= form.hidden_field :question_id, value: q.id %>
    </div>
  <% end %>

app/views/responses/_response.html.erb
<div id="<%= dom_id response %>">
  <p>
    <strong>Answer:</strong>
    <%= response.answer %>
  </p>

  <p>
    <strong>Question:</strong>
    <%= response.question_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= response.user_id %>
  </p>

</div>

app/views/responses/edit.html.erb
<% content_for :title, "Editing response" %>

<h1>Editing response</h1>

<%= render "form", response: @response %>

<br>

<div>
  <%= link_to "Show this response", @response %> |
  <%= link_to "Back to responses", responses_path %>
</div>

app/views/responses/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Responses" %>

<h1>Responses</h1>

<div id="responses">
  <% @responses.each do |response| %>
    <%= render response %>
    <p>
      <%= link_to "Show this response", response %>
    </p>
  <% end %>
</div>

<%= link_to "New response", new_response_path %>

app/views/responses/new.html.erb
<% content_for :title, "New response" %>

<h1>New response</h1>

<%= render "form", response: @response %>

<br>

<div>
  <%= link_to "Back to responses", responses_path %>
</div>

app/views/responses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @response %>

<div>
  <%= link_to "Edit this response", edit_response_path(@response) %> |
  <%= link_to "Back to responses", responses_path %>

  <%= button_to "Destroy this response", @response, method: :delete %>
</div>

app/views/responses/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@response.question, :response_form_frame) do %>
  <turbo_frame id=<%= dom_id(@response.question, :response_form_frame) %>>
    <%= render "responses/form", question: @response.question, response: @response  %>
  </turbo_frame>
<% end %>